In [34]:
import pandas as pd
import textwrap
from nltk.stem import PorterStemmer

In [35]:
df=pd.read_csv("fake_news_dataset.csv")

In [36]:
df.describe() #balanced classes

                 id         label
count  20800.000000  20800.000000
mean   10399.500000      0.500625
std     6004.587135      0.500012
min        0.000000      0.000000
25%     5199.750000      0.000000
50%    10399.500000      1.000000
75%    15599.250000      1.000000
max    20799.000000      1.000000

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      20800 non-null  int64
 1   title   20242 non-null  str
 2   author  18843 non-null  str
 3   text    20761 non-null  str
 4   label   20800 non-null  int64
dtypes: int64(2), str(3)
memory usage: 812.6 KB

In [23]:
df.head(10)

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1
5,5,Jackie Mason: Hollywood Would Love Trump if He...,Daniel Nussbaum,"In these trying times, Jackie Mason is the Voi...",0
6,6,Life: Life Of Luxury: Elton John’s 6 Favorite ...,NaN,Ever wonder how Britain’s most iconic pop pian...,1
7,7,Benoît Hamon Wins French Socialist Party’s Pre...,Alissa J. Rubin,"PARIS — France chose an idealistic, traditi...",0
8,8,Excerpts From a Draft Script for Donald Trump’...,NaN,Donald J. Trump is scheduled to make a highly ...,0
9,9,"A Back-Channel Plan for Ukraine and Russia, Co...",Megan Twohey and Scott Shane,A week before Michael T. Flynn resigned as nat...,0

In [24]:
df=df.dropna(subset=["text"])

In [25]:
#df.info() #checking

In [26]:
#fake news

# first_sample=df["text"].iloc[0]
# first_label=df["label"].iloc[0]

# print(f"Label : {first_label}\n")
# print(textwrap.fill(first_sample, width=60))

In [27]:
#not fake news

# second_sample=df["text"].iloc[1]
# second_label=df["label"].iloc[1]

# print(f"Label : {second_label}\n")
# print(textwrap.fill(second_sample, width=60))

In [28]:
def to_lowercase(df): # be careful about using it : could mix Apple (the brand) and apple (the fruit)
    df["title"] = df["title"].str.lower()
    df["text"] = df["text"].str.lower()
    return df

In [ ]:
#test
df_bis=df.copy()
df_bis=to_lowercase(df_bis)

sample=df_bis["text"].iloc[0]
print(textwrap.fill(sample, width=60))

house dem aide: we didn’t even see comey’s letter until
jason chaffetz tweeted it by darrell lucus on october 30,
2016 subscribe jason chaffetz on the stump in american fork,
utah ( image courtesy michael jolley, available under a
creative commons-by license)  with apologies to keith
olbermann, there is no doubt who the worst person in the
world is this week–fbi director james comey. but according
to a house democratic aide, it looks like we also know who
the second-worst person is as well. it turns out that when
comey sent his now-infamous letter announcing that the fbi
was looking into emails that may be related to hillary
clinton’s email server, the ranking democrats on the
relevant committees didn’t hear about it from comey. they
found out via a tweet from one of the republican committee
chairmen.  as we now know, comey notified the republican
chairmen and democratic ranking members of the house
intelligence, judiciary, and oversight committees that his
agency was reviewing emails it had recently discovered in
order to see if they contained classified information. not
long after this letter went out, oversight committee
chairman jason chaffetz set the political world ablaze with
this tweet. fbi dir just informed me, "the fbi has learned
of the existence of emails that appear to be pertinent to
the investigation." case reopened  — jason chaffetz
(@jasoninthehouse) october 28, 2016  of course, we now know
that this was not the case . comey was actually saying that
it was reviewing the emails in light of “an unrelated
case”–which we now know to be anthony weiner’s sexting with
a teenager. but apparently such little things as facts
didn’t matter to chaffetz. the utah republican had already
vowed to initiate a raft of investigations if hillary
wins–at least two years’ worth, and possibly an entire
term’s worth of them. apparently chaffetz thought the fbi
was already doing his work for him–resulting in a tweet that
briefly roiled the nation before cooler heads realized it
was a dud.  but according to a senior house democratic aide,
misreading that letter may have been the least of chaffetz’
sins. that aide told shareblue that his boss and other
democrats didn’t even know about comey’s letter at the
time–and only found out when they checked twitter.
“democratic ranking members on the relevant committees
didn’t receive comey’s letter until after the republican
chairmen. in fact, the democratic ranking members didn’
receive it until after the chairman of the oversight and
government reform committee, jason chaffetz, tweeted it out
and made it public.”  so let’s see if we’ve got this right.
the fbi director tells chaffetz and other gop committee
chairmen about a major development in a potentially
politically explosive investigation, and neither chaffetz
nor his other colleagues had the courtesy to let their
democratic counterparts know about it. instead, according to
this aide, he made them find out about it on twitter.  there
has already been talk on daily kos that comey himself
provided advance notice of this letter to chaffetz and other
republicans, giving them time to turn on the spin machine.
that may make for good theater, but there is nothing so far
that even suggests this is the case. after all, there is
nothing so far that suggests that comey was anything other
than grossly incompetent and tone-deaf.  what it does
suggest, however, is that chaffetz is acting in a way that
makes dan burton and darrell issa look like models of
responsibility and bipartisanship. he didn’t even have the
decency to notify ranking member elijah cummings about
something this explosive. if that doesn’t trample on basic
standards of fairness, i don’t know what does.  granted,
it’s not likely that chaffetz will have to answer for this.
he sits in a ridiculously republican district anchored in
provo and orem; it has a cook partisan voting index of r+25,
and gave mitt romney a punishing 78 percent of the vote in
2012. moreover, the republican house leadership has given
its full support to chaffetz’ planned fishing expedition.
but that doesn’t mean we can’t turn the hot lights on him.
after all, he is a textbook example of what the house has
become under republican control. and he is also the second
worst person in the world. about darrell lucus  darrell is a
30-something graduate of the university of north carolina
who considers himself a journalist of the old school. an
attempt to turn him into a member of the religious right in
college only succeeded in turning him into the religious
right's worst nightmare--a charismatic christian who is an
unapologetic liberal. his desire to stand up for those who
have been scared into silence only increased when he
survived an abusive three-year marriage. you may know him on
daily kos as christian dem in nc . follow him on twitter
@darrelllucus or connect with him on facebook . click here
to buy darrell a mello yello. connect

In [30]:
def delete_punctuation(df):
    df['text'] = df['text'].str.replace(r'[.,!?";()—–]', '', regex=True)
    return df

In [ ]:
#test
df_bis=df.copy()
df_bis=delete_punctuation(df_bis)

sample=df_bis["text"].iloc[0]
print(textwrap.fill(sample, width=60))

House Dem Aide: We Didn’t Even See Comey’s Letter Until
Jason Chaffetz Tweeted It By Darrell Lucus on October 30
2016 Subscribe Jason Chaffetz on the stump in American Fork
Utah  image courtesy Michael Jolley available under a
Creative Commons-BY license  With apologies to Keith
Olbermann there is no doubt who the Worst Person in The
World is this weekFBI Director James Comey But according to
a House Democratic aide it looks like we also know who the
second-worst person is as well It turns out that when Comey
sent his now-infamous letter announcing that the FBI was
looking into emails that may be related to Hillary Clinton’s
email server the ranking Democrats on the relevant
committees didn’t hear about it from Comey They found out
via a tweet from one of the Republican committee chairmen
As we now know Comey notified the Republican chairmen and
Democratic ranking members of the House Intelligence
Judiciary and Oversight committees that his agency was
reviewing emails it had recently discovered in order to see
if they contained classified information Not long after this
letter went out Oversight Committee Chairman Jason Chaffetz
set the political world ablaze with this tweet FBI Dir just
informed me The FBI has learned of the existence of emails
that appear to be pertinent to the investigation Case
reopened   Jason Chaffetz @jasoninthehouse October 28 2016
Of course we now know that this was not the case  Comey was
actually saying that it was reviewing the emails in light of
“an unrelated case”which we now know to be Anthony Weiner’s
sexting with a teenager But apparently such little things as
facts didn’t matter to Chaffetz The Utah Republican had
already vowed to initiate a raft of investigations if
Hillary winsat least two years’ worth and possibly an entire
term’s worth of them Apparently Chaffetz thought the FBI was
already doing his work for himresulting in a tweet that
briefly roiled the nation before cooler heads realized it
was a dud  But according to a senior House Democratic aide
misreading that letter may have been the least of Chaffetz’
sins That aide told Shareblue that his boss and other
Democrats didn’t even know about Comey’s letter at the
timeand only found out when they checked Twitter “Democratic
Ranking Members on the relevant committees didn’t receive
Comey’s letter until after the Republican Chairmen In fact
the Democratic Ranking Members didn’ receive it until after
the Chairman of the Oversight and Government Reform
Committee Jason Chaffetz tweeted it out and made it public”
So let’s see if we’ve got this right The FBI director tells
Chaffetz and other GOP committee chairmen about a major
development in a potentially politically explosive
investigation and neither Chaffetz nor his other colleagues
had the courtesy to let their Democratic counterparts know
about it Instead according to this aide he made them find
out about it on Twitter  There has already been talk on
Daily Kos that Comey himself provided advance notice of this
letter to Chaffetz and other Republicans giving them time to
turn on the spin machine That may make for good theater but
there is nothing so far that even suggests this is the case
After all there is nothing so far that suggests that Comey
was anything other than grossly incompetent and tone-deaf
What it does suggest however is that Chaffetz is acting in a
way that makes Dan Burton and Darrell Issa look like models
of responsibility and bipartisanship He didn’t even have the
decency to notify ranking member Elijah Cummings about
something this explosive If that doesn’t trample on basic
standards of fairness I don’t know what does  Granted it’s
not likely that Chaffetz will have to answer for this He
sits in a ridiculously Republican district anchored in Provo
and Orem it has a Cook Partisan Voting Index of R+25 and
gave Mitt Romney a punishing 78 percent of the vote in 2012
Moreover the Republican House leadership has given its full
support to Chaffetz’ planned fishing expedition But that
doesn’t mean we can’t turn the hot lights on him After all
he is a textbook example of what the House has become under
Republican control And he is also the Second Worst Person in
the World About Darrell Lucus  Darrell is a 30-something
graduate of the University of North Carolina who considers
himself a journalist of the old school An attempt to turn
him into a member of the religious right in college only
succeeded in turning him into the religious right's worst
nightmare--a charismatic Christian who is an unapologetic
liberal His desire to stand up for those who have been
scared into silence only increased when he survived an
abusive three-year marriage You may know him on Daily Kos as
Christian Dem in NC  Follow him on Twitter @DarrellLucus or
connect with him on Facebook  Click here to buy Darrell a
Mello Yello Connect

In [32]:
def stem_text(df):
    stemmer = PorterStemmer()
    words = df.split()
    stems = [stemmer.stem(word) for word in words]
    return " ".join(stems)

In [ ]:
#test
df_bis=df.copy()
df_bis["text_stemmed"] = df_bis["text"].apply(stem_text)
sample_stemmed=df_bis["text_stemmed"].iloc[0]
print(textwrap.fill(sample_stemmed, width=60))

hous dem aide: we didn’t even see comey’ letter until jason
chaffetz tweet it by darrel lucu on octob 30, 2016 subscrib
jason chaffetz on the stump in american fork, utah ( imag
courtesi michael jolley, avail under a creativ commons-bi
license) with apolog to keith olbermann, there is no doubt
who the worst person in the world is thi week–fbi director
jame comey. but accord to a hous democrat aide, it look like
we also know who the second-worst person is as well. it turn
out that when comey sent hi now-infam letter announc that
the fbi wa look into email that may be relat to hillari
clinton’ email server, the rank democrat on the relev
committe didn’t hear about it from comey. they found out via
a tweet from one of the republican committe chairmen. as we
now know, comey notifi the republican chairmen and democrat
rank member of the hous intelligence, judiciary, and
oversight committe that hi agenc wa review email it had
recent discov in order to see if they contain classifi
information. not long after thi letter went out, oversight
committe chairman jason chaffetz set the polit world ablaz
with thi tweet. fbi dir just inform me, "the fbi ha learn of
the exist of email that appear to be pertin to the
investigation." case reopen — jason chaffetz
(@jasoninthehouse) octob 28, 2016 of course, we now know
that thi wa not the case . comey wa actual say that it wa
review the email in light of “an unrel case”–which we now
know to be anthoni weiner’ sext with a teenager. but appar
such littl thing as fact didn’t matter to chaffetz. the utah
republican had alreadi vow to initi a raft of investig if
hillari wins–at least two years’ worth, and possibl an entir
term’ worth of them. appar chaffetz thought the fbi wa
alreadi do hi work for him–result in a tweet that briefli
roil the nation befor cooler head realiz it wa a dud. but
accord to a senior hous democrat aide, misread that letter
may have been the least of chaffetz’ sins. that aid told
shareblu that hi boss and other democrat didn’t even know
about comey’ letter at the time–and onli found out when they
check twitter. “democrat rank member on the relev committe
didn’t receiv comey’ letter until after the republican
chairmen. in fact, the democrat rank member didn’ receiv it
until after the chairman of the oversight and govern reform
committee, jason chaffetz, tweet it out and made it public.”
so let’ see if we’v got thi right. the fbi director tell
chaffetz and other gop committe chairmen about a major
develop in a potenti polit explos investigation, and neither
chaffetz nor hi other colleagu had the courtesi to let their
democrat counterpart know about it. instead, accord to thi
aide, he made them find out about it on twitter. there ha
alreadi been talk on daili ko that comey himself provid
advanc notic of thi letter to chaffetz and other
republicans, give them time to turn on the spin machine.
that may make for good theater, but there is noth so far
that even suggest thi is the case. after all, there is noth
so far that suggest that comey wa anyth other than grossli
incompet and tone-deaf. what it doe suggest, however, is
that chaffetz is act in a way that make dan burton and
darrel issa look like model of respons and bipartisanship.
he didn’t even have the decenc to notifi rank member elijah
cum about someth thi explosive. if that doesn’t trampl on
basic standard of fairness, i don’t know what does. granted,
it’ not like that chaffetz will have to answer for this. he
sit in a ridicul republican district anchor in provo and
orem; it ha a cook partisan vote index of r+25, and gave
mitt romney a punish 78 percent of the vote in 2012.
moreover, the republican hous leadership ha given it full
support to chaffetz’ plan fish expedition. but that doesn’t
mean we can’t turn the hot light on him. after all, he is a
textbook exampl of what the hous ha becom under republican
control. and he is also the second worst person in the
world. about darrel lucu darrel is a 30-someth graduat of
the univers of north carolina who consid himself a
journalist of the old school. an attempt to turn him into a
member of the religi right in colleg onli succeed in turn
him into the religi right' worst nightmare--a charismat
christian who is an unapologet liberal. hi desir to stand up
for those who have been scare into silenc onli increas when
he surviv an abus three-year marriage. you may know him on
daili ko as christian dem in nc . follow him on twitter
@darrelllucu or connect with him on facebook . click here to
buy darrel a mello yello. connect