In [28]:
import pandas as pd
import textwrap

In [2]:
df=pd.read_csv("fake_news_dataset.csv")

In [ ]:
df.describe() #balanced classes

                 id         label
count  20800.000000  20800.000000
mean   10399.500000      0.500625
std     6004.587135      0.500012
min        0.000000      0.000000
25%     5199.750000      0.000000
50%    10399.500000      1.000000
75%    15599.250000      1.000000
max    20799.000000      1.000000

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      20800 non-null  int64
 1   title   20242 non-null  str
 2   author  18843 non-null  str
 3   text    20761 non-null  str
 4   label   20800 non-null  int64
dtypes: int64(2), str(3)
memory usage: 812.6 KB

In [8]:
df.head(10)

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1
5,5,Jackie Mason: Hollywood Would Love Trump if He...,Daniel Nussbaum,"In these trying times, Jackie Mason is the Voi...",0
6,6,Life: Life Of Luxury: Elton John’s 6 Favorite ...,NaN,Ever wonder how Britain’s most iconic pop pian...,1
7,7,Benoît Hamon Wins French Socialist Party’s Pre...,Alissa J. Rubin,"PARIS — France chose an idealistic, traditi...",0
8,8,Excerpts From a Draft Script for Donald Trump’...,NaN,Donald J. Trump is scheduled to make a highly ...,0
9,9,"A Back-Channel Plan for Ukraine and Russia, Co...",Megan Twohey and Scott Shane,A week before Michael T. Flynn resigned as nat...,0

In [17]:
df=df.dropna(subset=["text"])

In [19]:
#df.info() #checking

In [34]:
#fake news

first_sample=df["text"].iloc[0]
first_label=df["label"].iloc[0]

print(f"Label : {first_label}\n")
print(textwrap.fill(first_sample, width=60))

Label : 1

House Dem Aide: We Didn’t Even See Comey’s Letter Until
Jason Chaffetz Tweeted It By Darrell Lucus on October 30,
2016 Subscribe Jason Chaffetz on the stump in American Fork,
Utah ( image courtesy Michael Jolley, available under a
Creative Commons-BY license)  With apologies to Keith
Olbermann, there is no doubt who the Worst Person in The
World is this week–FBI Director James Comey. But according
to a House Democratic aide, it looks like we also know who
the second-worst person is as well. It turns out that when
Comey sent his now-infamous letter announcing that the FBI
was looking into emails that may be related to Hillary
Clinton’s email server, the ranking Democrats on the
relevant committees didn’t hear about it from Comey. They
found out via a tweet from one of the Republican committee
chairmen.  As we now know, Comey notified the Republican
chairmen and Democratic ranking members of the House
Intelligence, Judiciary, and Oversight committees that his
agency was reviewing emails it had recently discovered in
order to see if they contained classified information. Not
long after this letter went out, Oversight Committee
Chairman Jason Chaffetz set the political world ablaze with
this tweet. FBI Dir just informed me, "The FBI has learned
of the existence of emails that appear to be pertinent to
the investigation." Case reopened  — Jason Chaffetz
(@jasoninthehouse) October 28, 2016  Of course, we now know
that this was not the case . Comey was actually saying that
it was reviewing the emails in light of “an unrelated
case”–which we now know to be Anthony Weiner’s sexting with
a teenager. But apparently such little things as facts
didn’t matter to Chaffetz. The Utah Republican had already
vowed to initiate a raft of investigations if Hillary
wins–at least two years’ worth, and possibly an entire
term’s worth of them. Apparently Chaffetz thought the FBI
was already doing his work for him–resulting in a tweet that
briefly roiled the nation before cooler heads realized it
was a dud.  But according to a senior House Democratic aide,
misreading that letter may have been the least of Chaffetz’
sins. That aide told Shareblue that his boss and other
Democrats didn’t even know about Comey’s letter at the
time–and only found out when they checked Twitter.
“Democratic Ranking Members on the relevant committees
didn’t receive Comey’s letter until after the Republican
Chairmen. In fact, the Democratic Ranking Members didn’
receive it until after the Chairman of the Oversight and
Government Reform Committee, Jason Chaffetz, tweeted it out
and made it public.”  So let’s see if we’ve got this right.
The FBI director tells Chaffetz and other GOP committee
chairmen about a major development in a potentially
politically explosive investigation, and neither Chaffetz
nor his other colleagues had the courtesy to let their
Democratic counterparts know about it. Instead, according to
this aide, he made them find out about it on Twitter.  There
has already been talk on Daily Kos that Comey himself
provided advance notice of this letter to Chaffetz and other
Republicans, giving them time to turn on the spin machine.
That may make for good theater, but there is nothing so far
that even suggests this is the case. After all, there is
nothing so far that suggests that Comey was anything other
than grossly incompetent and tone-deaf.  What it does
suggest, however, is that Chaffetz is acting in a way that
makes Dan Burton and Darrell Issa look like models of
responsibility and bipartisanship. He didn’t even have the
decency to notify ranking member Elijah Cummings about
something this explosive. If that doesn’t trample on basic
standards of fairness, I don’t know what does.  Granted,
it’s not likely that Chaffetz will have to answer for this.
He sits in a ridiculously Republican district anchored in
Provo and Orem; it has a Cook Partisan Voting Index of R+25,
and gave Mitt Romney a punishing 78 percent of the vote in
2012. Moreover, the Republican House leadership has given
its full support to Chaffetz’ planned fishing expedition.
But that doesn’t mean we can’t turn the hot lights on him.
After all, he is a textbook example of what the House has
become under Republican control. And he is also the Second
Worst Person in the World. About Darrell Lucus  Darrell is a
30-something graduate of the University of North Carolina
who considers himself a journalist of the old school. An
attempt to turn him into a member of the religious right in
college only succeeded in turning him into the religious
right's worst nightmare--a charismatic Christian who is an
unapologetic liberal. His desire to stand up for those who
have been scared into silence only increased when he
survived an abusive three-year marriage. You may know him on
Daily Kos as Christian Dem in NC . Follow him on Twitter
@DarrellLucus or connect with him on Facebook . Click here
to buy Darrell a Mello Yello. Connect

In [ ]:
#not fake news

second_sample=df["text"].iloc[1]
second_label=df["label"].iloc[1]

print(f"Label : {second_label}\n")
print(textwrap.fill(second_sample, width=60))

Label : 0

Ever get the feeling your life circles the roundabout rather
than heads in a straight line toward the intended
destination? [Hillary Clinton remains the big woman on
campus in leafy, liberal Wellesley, Massachusetts.
Everywhere else votes her most likely to don her
inauguration dress for the remainder of her days the way
Miss Havisham forever wore that wedding dress.  Speaking of
Great Expectations, Hillary Rodham overflowed with them 48
years ago when she first addressed a Wellesley graduating
class. The president of the college informed those gathered
in 1969 that the students needed “no debate so far as I
could ascertain as to who their spokesman was to be” (kind
of the like the Democratic primaries in 2016 minus the
terms unknown then even at a Seven Sisters school). “I am
very glad that Miss Adams made it clear that what I am
speaking for today is all of us —  the 400 of us,” Miss
Rodham told her classmates. After appointing herself Edger
Bergen to the Charlie McCarthys and Mortimer Snerds in
attendance, the    bespectacled in granny glasses (awarding
her matronly wisdom —  or at least John Lennon wisdom) took
issue with the previous speaker. Despite becoming the first
to win election to a seat in the U. S. Senate since
Reconstruction, Edward Brooke came in for criticism for
calling for “empathy” for the goals of protestors as he
criticized tactics. Though Clinton in her senior thesis on
Saul Alinsky lamented “Black Power demagogues” and “elitist
arrogance and repressive intolerance” within the New Left,
similar words coming out of a Republican necessitated a
brief rebuttal. “Trust,” Rodham ironically observed in 1969,
“this is one word that when I asked the class at our
rehearsal what it was they wanted me to say for them,
everyone came up to me and said ‘Talk about trust, talk
about the lack of trust both for us and the way we feel
about others. Talk about the trust bust.’ What can you say
about it? What can you say about a feeling that permeates a
generation and that perhaps is not even understood by those
who are distrusted?” The “trust bust” certainly busted
Clinton’s 2016 plans. She certainly did not even understand
that people distrusted her. After Whitewater, Travelgate,
the vast   conspiracy, Benghazi, and the missing emails,
Clinton found herself the distrusted voice on Friday. There
was a load of compromising on the road to the broadening of
her political horizons. And distrust from the American
people —  Trump edged her 48 percent to 38 percent on the
question immediately prior to November’s election —  stood
as a major reason for the closing of those horizons. Clinton
described her vanquisher and his supporters as embracing a
“lie,” a “con,” “alternative facts,” and “a   assault on
truth and reason. ” She failed to explain why the American
people chose his lies over her truth. “As the history majors
among you here today know all too well, when people in power
invent their own facts and attack those who question them,
it can mark the beginning of the end of a free society,” she
offered. “That is not hyperbole. ” Like so many people to
emerge from the 1960s, Hillary Clinton embarked upon a long,
strange trip. From high school Goldwater Girl and Wellesley
College Republican president to Democratic politician,
Clinton drank in the times and the place that gave her a
degree. More significantly, she went from idealist to cynic,
as a comparison of her two Wellesley commencement addresses
show. Way back when, she lamented that “for too long our
leaders have viewed politics as the art of the possible, and
the challenge now is to practice politics as the art of
making what appears to be impossible possible. ” Now, as the
big woman on campus but the odd woman out of the White
House, she wonders how her current station is even possible.
“Why aren’t I 50 points ahead?” she asked in September. In
May she asks why she isn’t president. The woman famously
dubbed a “congenital liar” by Bill Safire concludes that
lies did her in —  theirs, mind you, not hers. Getting stood
up on Election Day, like finding yourself the jilted bride
on your wedding day, inspires dangerous delusions.